site_name: OTN Glider Documentation
site_url: https://<org>.github.io/<repo>/

repo_url: https://github.com/<org>/<repo>
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
    - content.action.edit
    - search.suggest
    - search.highlight
    - content.tabs

nav:
  - Home: index.md
  - How-to Guides:
      - How to generate an SSH key pair: how/ssh-key.md
      - How to clone a GitLab repository with SSH: how/gitlab-repo-ssh.md
  - Glider Data Pipeline V1:
      - Overview: gdp/gdp.md
      - Class Diagram: gdp/overall_class_diagram.md
      - Pre-processing: gdp/pre_processing.md
      - Core-processing: gdp/core_processing.md
      - Post-processing: gdp/post_processing.md
      - Real-time Mission Flow: gdp/real-time_flow.md
      - Delayed Mission Flow: gdp/delayed_flow.md
      - Database and External Interfaces: gdp/database_and_api.md
      - Metadata in GDP: gdp/meta_data_netcdf.md
      - ERDDAP xml: gdp/erddap_xml.md
      - Customized GUTILS: gdp/customized_gutils.md

plugins:
  - search
  - mermaid2:
      version: 11.10.1

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - tables
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
